### ISSUE TITLE
Deleted from Chrome store?

### ISSUE THREAD

**Issue by IAkumaI** [jlawrence6809/CSS-Selector-Helper-for-Chrome#5]
Extension was deleted from chrome store. Why?

**Comment by jjl-genemod** [comment]
Thanks for the alert. The webstore requires updated permissions now. They didn't notify me and just pulled it off the store. I guess that's the infamous Google customer service.

**Comment by jjl-genemod** [comment]
I've updated the Chrome store and resubmitted it for review. You can always clone the repro and load the extension as unpacked if you can't use it right now.

**Comment by IAkumaI** [comment]
Sad, ext still deleted

**Comment by JoshKasap** [comment]
> I've updated the Chrome store and resubmitted it for review. You can always clone the repro and load the extension as unpacked if you can't use it right now.

Could you please update us on the plugin situation and or resubmit the plugin for review. This is easily one of the greatest plugins ever made for helping find selectors and I would love to be able to point people to an actual extension not a GitHub page.

**Comment by jlawrence6809** [comment]
Yeah sure I can try it again. They have really bad customer service and I'm thinking I can just resubmit it with a different dev account since it's only a few bucks to do. If you like the extension would you mind trying out a beta version I've made with a better ui? It still works the same way and has the same core code but looks a lot less jank. I wrote this when I was a baby dev years ago.

**Comment by jlawrence6809** [comment]
I'm closing this out as solved!
